name: Heroku pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:

   runs-on: ubuntu-latest

   steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: akhileshns/heroku-deploy@v3.8.9 
        with:
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          usedocker: true  
